### PR TITLE
[ADD] in BR/Cost control the total revenue should be changed into the company currency.

### PR DESCRIPTION
**Pull request by cialuo**
[ADD] in BR/Cost control the total revenue should be changed into the company currency.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/31%23issuecomment-196760845%22%2C%20%22https%3A//github.com/xie8899/project/pull/31%23issuecomment-197112430%22%2C%20%22https%3A//github.com/xie8899/project/pull/31%23issuecomment-197125359%22%2C%20%22https%3A//github.com/xie8899/project/pull/31%23issuecomment-197200218%22%2C%20%22https%3A//github.com/xie8899/project/pull/31%23issuecomment-197227120%22%2C%20%22https%3A//github.com/xie8899/project/pull/31%23issuecomment-197229332%22%2C%20%22https%3A//github.com/xie8899/project/pull/31%23issuecomment-197229490%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/31%23issuecomment-196760845%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20is%20about%20company_id%20%28which%20was%20not%20asked%29%20and%20nothing%20about%20currency.%22%2C%20%22created_at%22%3A%20%222016-03-15T10%3A40%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40elicoidal%20the%20company_id%20is%20for%20currency%2C%20and%20at%20other%20branch%20to%20compute%20the%20total%20revenue.%20https%3A//github.com/xie8899/project/pull/32%2C%20%22%2C%20%22created_at%22%3A%20%222016-03-16T02%3A01%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7767792%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cialuo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40cialuo%20we%20did%20not%20need%20Company%20in%20the%20BR%20%28it%20is%20OK%20to%20have%20it%20now%29.%20you%20just%20need%20to%20test%20the%20res_user.company_id%20to%20check%20the%20rates%5Cr%5CnIf%20you%20have%20company_id%20you%20should%20create%20the%20corresponding%20multi-company%20rules%22%2C%20%22created_at%22%3A%20%222016-03-16T02%3A49%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40cialuo%20%20you%20need%20to%20deal%20with%20the%20existing%20data%20no%3F%22%2C%20%22created_at%22%3A%20%222016-03-16T07%3A50%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%2C%20%7B%22body%22%3A%20%22by%20default%20set%20no%20company%20it%20is%20fine%5Cr%5Cnactually%20it%20should%20be%20possible%20to%20be%20multi%20company%20and%20if%20that%20is%20the%20case%20then%20we%20fall%20back%20to%20the%20res_user.company_id%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-03-16T09%3A32%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%2C%20let%27s%20merge%20this%20PR%20first.%20%40cialuo%20make%20another%20PR%20to%20add%20rules%22%2C%20%22created_at%22%3A%20%222016-03-16T09%3A41%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-16T09%3A41%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/31#issuecomment-196760845'>General Comment</a></b>
- <a href='https://github.com/elicoidal'></a> This is about company_id (which was not asked) and nothing about currency.
- <a href='https://github.com/cialuo'></a> @elicoidal the company_id is for currency, and at other branch to compute the total revenue. https://github.com/xie8899/project/pull/32,
- <a href='https://github.com/elicoidal'></a> @cialuo we did not need Company in the BR (it is OK to have it now). you just need to test the res_user.company_id to check the rates
  If you have company_id you should create the corresponding multi-company rules
- <a href='https://github.com/duanyp1991'></a> @cialuo  you need to deal with the existing data no?
- <a href='https://github.com/elicoidal'></a> by default set no company it is fine
  actually it should be possible to be multi company and if that is the case then we fall back to the res_user.company_id
- <a href='https://github.com/duanyp1991'></a> LGTM, let's merge this PR first. @cialuo make another PR to add rules
- <a href='https://github.com/siyuancn'></a> LGTM

<a href='https://www.codereviewhub.com/xie8899/project/pull/31?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/31?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/31'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/31'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by elicoidal** [comment]
This is about company_id (which was not asked) and nothing about currency.

**Comment by cialuo** [comment]
@elicoidal the company_id is for currency, and at other branch to compute the total revenue. https://github.com/xie8899/project/pull/32,

**Comment by elicoidal** [comment]
@cialuo we did not need Company in the BR (it is OK to have it now). you just need to test the res_user.company_id to check the rates
If you have company_id you should create the corresponding multi-company rules

**Comment by duanyp1991** [comment]
@cialuo  you need to deal with the existing data no?

**Comment by elicoidal** [comment]
by default set no company it is fine
actually it should be possible to be multi company and if that is the case then we fall back to the res_user.company_id

**Comment by duanyp1991** [comment]
LGTM, let's merge this PR first. @cialuo make another PR to add rules

**Comment by siyuancn** [comment]
LGTM

**Pull request merged**
