### PR TITLE
[FIX] business_requirement_deliverable: Issue-3480: Change the resour…

### PR DESCRIPTION
**Pull request by martintorresvm**
…ce type default to "Task"
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/26%23issuecomment-194643973%22%2C%20%22https%3A//github.com/xie8899/project/pull/26%23issuecomment-194644807%22%2C%20%22https%3A//github.com/xie8899/project/pull/26%23issuecomment-194645012%22%2C%20%22https%3A//github.com/xie8899/project/pull/26%23issuecomment-194653069%22%2C%20%22https%3A//github.com/xie8899/project/pull/26%23issuecomment-194653644%22%2C%20%22https%3A//github.com/xie8899/project/pull/26%23issuecomment-194653763%22%2C%20%22https%3A//github.com/xie8899/project/pull/26%23issuecomment-194653905%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/26%23issuecomment-194643973%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-10T03%3A32%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-10T03%3A38%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40siyuancn%20please%20deploy%20in%20stable%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-03-10T03%3A38%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40elicoidal%20can%20you%20merge%20pull%20request%20first%3F%22%2C%20%22created_at%22%3A%20%222016-03-10T04%3A02%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%2C%20%7B%22body%22%3A%20%22no%22%2C%20%22created_at%22%3A%20%222016-03-10T04%3A05%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20have%20no%20write%20access%20on%20htis%20repo%22%2C%20%22created_at%22%3A%20%222016-03-10T04%3A06%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40duanyp1991%20%40xie8899%20can%20you%20merge%20it%3F%22%2C%20%22created_at%22%3A%20%222016-03-10T04%3A07%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/26#issuecomment-194643973'>General Comment</a></b>
- <a href='https://github.com/siyuancn'></a> LGTM
- <a href='https://github.com/elicoidal'></a> LGTM
- <a href='https://github.com/elicoidal'></a> @siyuancn please deploy in stable
- <a href='https://github.com/siyuancn'></a> @elicoidal can you merge pull request first?
- <a href='https://github.com/elicoidal'></a> no
- <a href='https://github.com/elicoidal'></a> I have no write access on htis repo
- <a href='https://github.com/siyuancn'></a> @duanyp1991 @xie8899 can you merge it?

<a href='https://www.codereviewhub.com/xie8899/project/pull/26?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/26?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/26'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/26'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by siyuancn** [comment]
LGTM

**Comment by elicoidal** [comment]
LGTM

**Comment by elicoidal** [comment]
@siyuancn please deploy in stable

**Comment by siyuancn** [comment]
@elicoidal can you merge pull request first?

**Comment by elicoidal** [comment]
no

**Comment by elicoidal** [comment]
I have no write access on htis repo

**Comment by siyuancn** [comment]
@duanyp1991 @xie8899 can you merge it?

**Pull request merged**
