### PR TITLE
[FIX] Gap analysis crm 8.0.2 business requirement cost sales price related issues

### PR DESCRIPTION
**Pull request by cialuo**
Gap analysis crm 8.0.2 business requirement cost sales price related issues
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/29%23issuecomment-196231621%22%2C%20%22https%3A//github.com/xie8899/project/pull/29%23issuecomment-196591037%22%2C%20%22https%3A//github.com/xie8899/project/pull/29%23issuecomment-196591136%22%2C%20%22https%3A//github.com/xie8899/project/pull/29%23issuecomment-196595071%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/29%23issuecomment-196231621%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-03-14T09%3A54%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-15T01%3A03%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40cialuo%20please%20merge%22%2C%20%22created_at%22%3A%20%222016-03-15T01%3A03%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40siyuan%20%40cialuo%20%20Please%20put%20module%3A%20%2A%2Abusiness_requirement_crm%2A%2A%20from%20branch%3A%2A%2Agap_analysis_crm_8.0.2%2A%2A%20to%20server.%22%2C%20%22created_at%22%3A%20%222016-03-15T01%3A15%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/29#issuecomment-196231621'>General Comment</a></b>
- <a href='https://github.com/duanyp1991'></a> LGTM
- <a href='https://github.com/elicoidal'></a> LGTM
- <a href='https://github.com/elicoidal'></a> @cialuo please merge
- <a href='https://github.com/duanyp1991'></a> @siyuan @cialuo  Please put module: **business_requirement_crm** from branch:**gap_analysis_crm_8.0.2** to server.

<a href='https://www.codereviewhub.com/xie8899/project/pull/29?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/29?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/29'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/29'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by duanyp1991** [comment]
LGTM

**Comment by elicoidal** [comment]
LGTM

**Comment by elicoidal** [comment]
@cialuo please merge

**Comment by duanyp1991** [comment]
@siyuan @cialuo  Please put module: **business_requirement_crm** from branch:**gap_analysis_crm_8.0.2** to server.

**Pull request merged**
