### PR TITLE
[FIX] Fixed business requirement cost & sales price related issues

### PR DESCRIPTION
**Pull request by cialuo**
Gap analysis 8.0.2 add order
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/24%23issuecomment-196231795%22%2C%20%22https%3A//github.com/xie8899/project/pull/24%23issuecomment-196590197%22%2C%20%22https%3A//github.com/xie8899/project/pull/24%23issuecomment-196596233%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/24%23issuecomment-196231795%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-14T09%3A54%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%2C%20%7B%22body%22%3A%20%22title%20has%20nothing%20to%20do%20with%20the%20fix.%20Other%20than%20that%20LGTM%22%2C%20%22created_at%22%3A%20%222016-03-15T00%3A58%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40siyuan%20%40cialuo%20%20Please%20copy%20%60business_requirement%60%20module%20from%20branch%3A%60%20gap_analysis_8.0.2%60.%22%2C%20%22created_at%22%3A%20%222016-03-15T01%3A18%3A36Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/24#issuecomment-196231795'>General Comment</a></b>
- <a href='https://github.com/duanyp1991'></a> LGTM
- <a href='https://github.com/elicoidal'></a> title has nothing to do with the fix. Other than that LGTM
- <a href='https://github.com/duanyp1991'></a> @siyuan @cialuo  Please copy `business_requirement` module from branch:`gap_analysis_8.0.2`.

<a href='https://www.codereviewhub.com/xie8899/project/pull/24?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/24?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/24'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/24'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by duanyp1991** [comment]
LGTM

**Comment by elicoidal** [comment]
title has nothing to do with the fix. Other than that LGTM

**Comment by duanyp1991** [comment]
@siyuan @cialuo  Please copy `business_requirement` module from branch:`gap_analysis_8.0.2`.

**Pull request merged**
