### PR TITLE
[FIX] business_requirement_deliverable_default: Issue related to the …

### PR DESCRIPTION
**Pull request by martintorresvm**
…deletion of a BR that have resources that comes from a product
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/37%23issuecomment-199181027%22%2C%20%22https%3A//github.com/xie8899/project/pull/37%23issuecomment-199187859%22%2C%20%22https%3A//github.com/xie8899/project/pull/37%23issuecomment-199191712%22%2C%20%22https%3A//github.com/xie8899/project/pull/37%23issuecomment-199203399%22%2C%20%22https%3A//github.com/xie8899/project/pull/37%23issuecomment-199204890%22%2C%20%22https%3A//github.com/xie8899/project/pull/37%23issuecomment-199655278%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/37%23issuecomment-199181027%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22it%20is%20not%20only%20delete%20but%20also%20update.%5Cr%5CnIt%20seems%20that%20the%20resources%20lines%20are%20not%20created%20from%20template%20but%20linked%20to%20it%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-03-21T08%3A52%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-21T09%3A18%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40elicoidal%20should%20I%20deploy%20it%20on%20the%20stable%3F%22%2C%20%22created_at%22%3A%20%222016-03-21T09%3A31%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%2C%20%7B%22body%22%3A%20%22yes%5Cr%5Cn%28tested%29%22%2C%20%22created_at%22%3A%20%222016-03-21T09%3A58%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40xie8899%20could%20you%20accept%20the%20pull%20request%3F%22%2C%20%22created_at%22%3A%20%222016-03-21T10%3A00%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40siyuancn%20%20I%20merged%20this%20PR.%22%2C%20%22created_at%22%3A%20%222016-03-22T06%3A23%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/37#issuecomment-199181027'>General Comment</a></b>
- <a href='https://github.com/elicoidal'></a> it is not only delete but also update.
  It seems that the resources lines are not created from template but linked to it
- <a href='https://github.com/siyuancn'></a> LGTM
- <a href='https://github.com/siyuancn'></a> @elicoidal should I deploy it on the stable?
- <a href='https://github.com/elicoidal'></a> yes
  (tested)
- <a href='https://github.com/siyuancn'></a> @xie8899 could you accept the pull request?
- <a href='https://github.com/duanyp1991'></a> @siyuancn  I merged this PR.

<a href='https://www.codereviewhub.com/xie8899/project/pull/37?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/37?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/37'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by elicoidal** [comment]
it is not only delete but also update.
It seems that the resources lines are not created from template but linked to it

**Comment by siyuancn** [comment]
LGTM

**Comment by siyuancn** [comment]
@elicoidal should I deploy it on the stable?

**Comment by elicoidal** [comment]
yes
(tested)

**Comment by siyuancn** [comment]
@xie8899 could you accept the pull request?

**Comment by duanyp1991** [comment]
@siyuancn  I merged this PR.

**Pull request merged**
