### PR TITLE
[FIX] business_requirement_deliverable_report: Issue related with res…

### PR DESCRIPTION
**Pull request by martintorresvm**
…ource lines could not print the quantity if it's less than unit, fix template_business_requirement_deliverable_resources.docx file

cc @duanyp1991 @elicoidal
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-216481125%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-216484065%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-216820318%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-216821630%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-216844870%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-217058134%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-217069676%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-217086925%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-217087331%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-217097070%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-217107871%22%2C%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-217110011%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/45%23issuecomment-216481125%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Weird%20the%20.docx%20file%20is%20considered%20as%20binary.%20I%20though%20it%20was%20an%20XML%20file%20%28or%20maybe%20it%27s%20because%20it%27s%20zipped%29.%22%2C%20%22created_at%22%3A%20%222016-05-03T09%3A40%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10879075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/seb-elico%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40victormartinelicocorp%20can%20you%20add%20as%20a%20comment%20the%20difference%20between%20the%20previous%20and%20new%20template%20so%20that%20we%20can%20check%20if%20it%27s%20ok%20or%20not%3F%22%2C%20%22created_at%22%3A%20%222016-05-03T09%3A56%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10879075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/seb-elico%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40seb-elico%20.%20I%20change%20this%20variable%20%60%7B%7Bline.qty%7Cint%7D%7D%60%20for%20%60%7B%7Bline.qty%7D%7D%60%20what%20it%20means%20not%20use%20a%20filter%20on%20Jinja2%20means%20convert%20float%20to%20integer%20the%20content%20of%20line.qty.%20So%200.xxxx%20allways%20was%200.%22%2C%20%22created_at%22%3A%20%222016-05-04T10%3A12%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/16461806%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/victormartinelicocorp%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-05-04T10%3A19%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10879075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/seb-elico%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%5Cr%5CnNevertheless%20this%20not%20the%20only%20feedback%20to%20improve%20for%20the%20report.%5Cr%5CnThere%20are%20ACL%20issues%20%28cannot%20print%20if%20BR%20cost%20group%29%20%2B%20currency%20%2B%20wrong%20data%20in%20many%20places%20%28%40seb-elico%29%20have%20a%20list.%5Cr%5CnBesides%20we%20need%20to%20add%20a%20page%20break%20before%20every%20deliverable%22%2C%20%22created_at%22%3A%20%222016-05-04T12%3A28%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40elicoidal%20I%20update%20the%20information%20with%20your%20comment%20for%20the%20Task%3A%2012214%20New%20module%20business_requirement_deliverable_report.%5Cr%5Cn%5Cr%5CnAbout%20the%20ACL%20issues%20%28cannot%20print%20if%20BR%20cost%20group%29%20I%20think%20it%27s%20solved%20with%20the%3A%5Cr%5Cnhttps%3A//github.com/xie8899/project/pull/46%5Cr%5Cn%5Cr%5CnCurrency%20%28and%20the%20properly%20Price%20List%29%20depends%20on%20an%20%5C%22Issue-3479-business%20requirement%20cost%20%26%20sales%20price%5C%22%20assigned%20to%20Luke.%20I%20talked%20he%20yesterday%20but%20he%20is%20very%20busy%20now.%20I%27ll%20try%20to%20work%20on%20it%20if%20also%20I%20have%20time.%5Cr%5Cn%5Cr%5CnWrong%20data%20in%20many%20places%20and%20add%20a%20page%20break%20before%20every%20deliverable.%20Could%20be%20done%20if%20I%20have%20that%20list.%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-05-05T02%3A03%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/16461806%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/victormartinelicocorp%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27ve%20briefed%20Victor%20about%20the%20other%20issues%22%2C%20%22created_at%22%3A%20%222016-05-05T03%3A25%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10879075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/seb-elico%22%7D%7D%2C%20%7B%22body%22%3A%20%22OK%3A%20thanks%20%40victormartinelicocorp%20%22%2C%20%22created_at%22%3A%20%222016-05-05T06%3A38%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40seb-elico%20please%20make%20sure%20to%20deploy%20asap%20for%20test%22%2C%20%22created_at%22%3A%20%222016-05-05T06%3A43%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20fix%20the%20format%20and%20put%20the%20correct%20quantities%20for%20the%20price%20of%20Deliverable%20Lines%20%60unit_price%60%20and%20%60price_total%60.%5Cr%5Cncc%20%40duanyp1991%20%40elicoidal%22%2C%20%22created_at%22%3A%20%222016-05-05T07%3A59%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/16461806%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/victormartinelicocorp%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40victormartinelicocorp%20can%20you%20please%20upload%20an%20example%20of%20PDF%20so%20that%20we%20can%20confirm%20this%20is%20ok%20now%3F%20%28since%20we%20can%27t%20compare%20the%20docx%29%22%2C%20%22created_at%22%3A%20%222016-05-05T09%3A08%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10879075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/seb-elico%22%7D%7D%2C%20%7B%22body%22%3A%20%22Best%20is%20to%20deploy%20and%20test%20the%20report%22%2C%20%22created_at%22%3A%20%222016-05-05T09%3A17%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/45#issuecomment-216481125'>General Comment</a></b>
- <a href='https://github.com/seb-elico'></a> Weird the .docx file is considered as binary. I though it was an XML file (or maybe it's because it's zipped).
- <a href='https://github.com/seb-elico'></a> @victormartinelicocorp can you add as a comment the difference between the previous and new template so that we can check if it's ok or not?
- <a href='https://github.com/victormartinelicocorp'></a> @seb-elico . I change this variable `{{line.qty|int}}` for `{{line.qty}}` what it means not use a filter on Jinja2 means convert float to integer the content of line.qty. So 0.xxxx allways was 0.
- <a href='https://github.com/seb-elico'></a> LGTM
- <a href='https://github.com/elicoidal'></a> LGTM
  Nevertheless this not the only feedback to improve for the report.
  There are ACL issues (cannot print if BR cost group) + currency + wrong data in many places (@seb-elico) have a list.
  Besides we need to add a page break before every deliverable
- <a href='https://github.com/victormartinelicocorp'></a> @elicoidal I update the information with your comment for the Task: 12214 New module business_requirement_deliverable_report.
  About the ACL issues (cannot print if BR cost group) I think it's solved with the:
  https://github.com/xie8899/project/pull/46
  Currency (and the properly Price List) depends on an "Issue-3479-business requirement cost & sales price" assigned to Luke. I talked he yesterday but he is very busy now. I'll try to work on it if also I have time.
  Wrong data in many places and add a page break before every deliverable. Could be done if I have that list.
- <a href='https://github.com/seb-elico'></a> I've briefed Victor about the other issues
- <a href='https://github.com/elicoidal'></a> OK: thanks @victormartinelicocorp
- <a href='https://github.com/elicoidal'></a> @seb-elico please make sure to deploy asap for test
- <a href='https://github.com/victormartinelicocorp'></a> I fix the format and put the correct quantities for the price of Deliverable Lines `unit_price` and `price_total`.
  cc @duanyp1991 @elicoidal
- <a href='https://github.com/seb-elico'></a> @victormartinelicocorp can you please upload an example of PDF so that we can confirm this is ok now? (since we can't compare the docx)
- <a href='https://github.com/elicoidal'></a> Best is to deploy and test the report

<a href='https://www.codereviewhub.com/xie8899/project/pull/45?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/45?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/45'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/45'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by seb-elico** [comment]
Weird the .docx file is considered as binary. I thought it was an XML file (or maybe it's because it's zipped).

**Comment by seb-elico** [comment]
@victormartinelicocorp can you add as a comment the difference between the previous and new template so that we can check if it's ok or not?

**Comment by martintorresvm** [comment]
@seb-elico . I change this variable `{{line.qty|int}}` for `{{line.qty}}` what it means not use a filter on Jinja2 means convert float to integer the content of line.qty. So 0.xxxx allways was 0.

**Comment by seb-elico** [comment]
LGTM

**Comment by elicoidal** [comment]
LGTM
Nevertheless this not the only feedback to improve for the report.
There are ACL issues (cannot print if BR cost group) + currency + wrong data in many places (@seb-elico) have a list.
Besides we need to add a page break before every deliverable

**Comment by martintorresvm** [comment]
@elicoidal I update the information with your comment for the Task: 12214 New module business_requirement_deliverable_report.

About the ACL issues (cannot print if BR cost group) I think it's solved with the:
https://github.com/xie8899/project/pull/46

Currency (and the properly Price List) depends on an "Issue-3479-business requirement cost & sales price" assigned to Luke. I talked he yesterday but he is very busy now. I'll try to work on it if also I have time.

Wrong data in many places and add a page break before every deliverable. Could be done if I have that list.

**Comment by seb-elico** [comment]
I've briefed Victor about the other issues

**Comment by elicoidal** [comment]
OK: thanks @victormartinelicocorp

**Comment by elicoidal** [comment]
@seb-elico please make sure to deploy asap for test

**Comment by martintorresvm** [comment]
I fix the format and put the correct quantities for the price of Deliverable Lines `unit_price` and `price_total`.
cc @duanyp1991 @elicoidal

**Comment by seb-elico** [comment]
@victormartinelicocorp can you please upload an example of PDF so that we can confirm this is ok now? (since we can't compare the docx)

**Comment by elicoidal** [comment]
Best is to deploy and test the report

**Pull request merged**
