### PR TITLE
[FIX] business_requirement_crm: crm_make_sale.py, crm_make_sale_view.…

### PR DESCRIPTION
**Pull request by martintorresvm**
…xml, README.rst, **openerp**.py (Issue 3443,Task 12682)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/21%23issuecomment-192050464%22%2C%20%22https%3A//github.com/xie8899/project/pull/21%23issuecomment-193039139%22%2C%20%22https%3A//github.com/xie8899/project/pull/21%23issuecomment-193041674%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/21%23issuecomment-192050464%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-04T01%3A37%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-07T01%3A39%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-03-07T01%3A47%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/21#issuecomment-192050464'>General Comment</a></b>
- <a href='https://github.com/duanyp1991'></a> LGTM
- <a href='https://github.com/siyuancn'></a> LGTM

<a href='https://www.codereviewhub.com/xie8899/project/pull/21?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/21?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/21'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/21'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by duanyp1991** [comment]
LGTM

**Comment by siyuancn** [comment]
LGTM

**Comment by duanyp1991** [comment]
:+1:

**Pull request merged**
