### PR TITLE
[FIX] issue-error-when-saving-an-opportunity-4

### PR DESCRIPTION
**Pull request by cialuo**
[FIX] issue-error-when-saving-an-opportunity-4
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/28%23issuecomment-195168770%22%2C%20%22https%3A//github.com/xie8899/project/pull/28%23issuecomment-195170551%22%2C%20%22https%3A//github.com/xie8899/project/pull/28%23issuecomment-195171107%22%2C%20%22https%3A//github.com/xie8899/project/pull/28%23issuecomment-195171230%22%2C%20%22https%3A//github.com/xie8899/project/pull/28%23issuecomment-195171543%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/28%23issuecomment-195168770%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40duanyp1991%20%22%2C%20%22created_at%22%3A%20%222016-03-11T04%3A09%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7767792%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cialuo%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-11T04%3A12%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-03-11T04%3A16%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20cannot%20merge%20or%20deploy%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-03-11T04%3A16%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%27ll%20do%20the%20deploy%20now%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-03-11T04%3A17%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/28#issuecomment-195168770'>General Comment</a></b>
- <a href='https://github.com/cialuo'></a> @duanyp1991
- <a href='https://github.com/duanyp1991'></a> LGTM
- <a href='https://github.com/elicoidal'></a> LGTM
- <a href='https://github.com/elicoidal'></a> I cannot merge or deploy
- <a href='https://github.com/duanyp1991'></a> I'll do the deploy now

<a href='https://www.codereviewhub.com/xie8899/project/pull/28?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/28?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/28'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/28'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by cialuo** [comment]
@duanyp1991

**Comment by duanyp1991** [comment]
LGTM

**Comment by elicoidal** [comment]
LGTM

**Comment by elicoidal** [comment]
I cannot merge or deploy

**Comment by duanyp1991** [comment]
I'll do the deploy now

**Pull request merged**
