### PR TITLE
[FIX] business_requirement_deliverable_report: Issue related with ACL…

### PR DESCRIPTION
**Pull request by martintorresvm**
… business_requirement_deliverable lines and project, the BR user can not print BR's, fix business_requirement_deliverable_report.py file

cc @elicoidal @duanyp1991
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/46%23issuecomment-216737065%22%2C%20%22https%3A//github.com/xie8899/project/pull/46%23issuecomment-216737146%22%2C%20%22https%3A//github.com/xie8899/project/pull/46%23issuecomment-216779947%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/46%23issuecomment-216737065%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-05-04T04%3A13%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-05-04T04%3A13%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12975184%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/siyuancn%22%7D%7D%2C%20%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-05-04T08%3A19%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/46#issuecomment-216737065'>General Comment</a></b>
- <a href='https://github.com/siyuancn'></a> LGTM
- <a href='https://github.com/siyuancn'></a> LGTM
- <a href='https://github.com/elicoidal'></a> LGTM

<a href='https://www.codereviewhub.com/xie8899/project/pull/46?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/46?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/46'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/46'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by siyuancn** [comment]
LGTM

**Comment by siyuancn** [comment]
LGTM

**Comment by elicoidal** [comment]
LGTM

**Pull request merged**
