### PR TITLE
[FIX] Fixed resource issue

### PR DESCRIPTION
**Pull request by cialuo**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/40%23issuecomment-202256155%22%2C%20%22https%3A//github.com/xie8899/project/pull/40%23issuecomment-202256209%22%2C%20%22https%3A//github.com/xie8899/project/pull/40%23issuecomment-202281145%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/40%23issuecomment-202256155%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%2C%20%40eric%2C%20issue%20is%20different%20than%20last%20time.%22%2C%20%22created_at%22%3A%20%222016-03-28T06%3A24%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3785252%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/duanyp1991%22%7D%7D%2C%20%7B%22body%22%3A%20%22Wrong%20Eric%20%22%2C%20%22created_at%22%3A%20%222016-03-28T06%3A25%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/470%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/eric%22%7D%7D%2C%20%7B%22body%22%3A%20%22lgtm%22%2C%20%22created_at%22%3A%20%222016-03-28T07%3A28%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/40#issuecomment-202256155'>General Comment</a></b>
- <a href='https://github.com/duanyp1991'></a> LGTM, @eric, issue is different than last time.
- <a href='https://github.com/eric'></a> Wrong Eric
- <a href='https://github.com/elicoidal'></a> lgtm

<a href='https://www.codereviewhub.com/xie8899/project/pull/40?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/40?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/40'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/40'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by duanyp1991** [comment]
LGTM, @elicoidal, issue is different than last time.

**Comment by eric** [comment]
Wrong Eric

**Comment by elicoidal** [comment]
lgtm

**Pull request merged**
