### PR TITLE
[IMP]: business_requirement: Improve module based on BR000320 create …

### PR DESCRIPTION
**Pull request by martintorresvm**
…business_requirement bases on email alias (set the default project) and incoming mail server (action to perform)

cc @duanyp1991 @elicoidal
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/xie8899/project/pull/44%23issuecomment-211789751%22%2C%20%22https%3A//github.com/xie8899/project/pull/44%23issuecomment-211789907%22%2C%20%22https%3A//github.com/xie8899/project/pull/44%23issuecomment-212208878%22%2C%20%22https%3A//github.com/xie8899/project/pull/44%23issuecomment-212357208%22%2C%20%22https%3A//github.com/xie8899/project/pull/44%23issuecomment-212379146%22%2C%20%22https%3A//github.com/xie8899/project/pull/44%23issuecomment-212379733%22%2C%20%22https%3A//github.com/xie8899/project/pull/44%23issuecomment-212382536%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/xie8899/project/pull/44%23issuecomment-211789751%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22LGTM%22%2C%20%22created_at%22%3A%20%222016-04-19T08%3A19%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40duanyp1991%20Can%20you%20have%20a%20look%20so%20that%20we%20can%20deploy%20asap%3F%22%2C%20%22created_at%22%3A%20%222016-04-19T08%3A20%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40victormartinelicocorp%20I%20thought%20you%20were%20supposed%20to%20port%20it%20to%20new%20API.%20It%20wasn%27t%20possible%3F%5Cr%5CnAlso%2C%20I%20would%20like%20to%20try%20it%20with%20you%20first%20in%20order%20to%20test%20emails%20with%20attachments%20and%20pictures.%20I%20think%20we%20should%20implement%20something%20similar%20to%20issues%3A%20put%20the%20full%20email%20as%20a%20message%20in%20the%20conversation%20so%20that%20we%20don%27t%20lose%20images/attachments%20and%20formatting.%22%2C%20%22created_at%22%3A%20%222016-04-20T02%3A02%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10879075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/seb-elico%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40victormartinelicocorp%20for%20new%20API%3A%20check%20odoo/master%20there%20are%20plenty%20example.%5Cr%5Cndont%20block%20this%20PR%20for%20this%20though%22%2C%20%22created_at%22%3A%20%222016-04-20T09%3A54%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40seb-elico%20would%20you%20agree%20to%20merge%20and%20have%20a%20new%20PR%20for%20the%20migration%20to%20new%20API%3F%22%2C%20%22created_at%22%3A%20%222016-04-20T10%3A54%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40elicoidal%20new%20API%20is%20not%20blocking%20indeed.%20However%2C%20my%20comment%20about%20creating%20a%20message%20in%20the%20thread%20is%20still%20valid%21%20I%20don%27t%20want%20to%20lose%20images/attachments%22%2C%20%22created_at%22%3A%20%222016-04-20T10%3A57%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/10879075%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/seb-elico%22%7D%7D%2C%20%7B%22body%22%3A%20%22Agree%22%2C%20%22created_at%22%3A%20%222016-04-20T11%3A05%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/7600613%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/elicoidal%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/xie8899/project/pull/44#issuecomment-211789751'>General Comment</a></b>
- <a href='https://github.com/elicoidal'></a> LGTM
- <a href='https://github.com/elicoidal'></a> @duanyp1991 Can you have a look so that we can deploy asap?
- <a href='https://github.com/seb-elico'></a> @victormartinelicocorp I thought you were supposed to port it to new API. It wasn't possible?
  Also, I would like to try it with you first in order to test emails with attachments and pictures. I think we should implement something similar to issues: put the full email as a message in the conversation so that we don't lose images/attachments and formatting.
- <a href='https://github.com/elicoidal'></a> @victormartinelicocorp for new API: check odoo/master there are plenty example.
  dont block this PR for this though
- <a href='https://github.com/elicoidal'></a> @seb-elico would you agree to merge and have a new PR for the migration to new API?
- <a href='https://github.com/seb-elico'></a> @elicoidal new API is not blocking indeed. However, my comment about creating a message in the thread is still valid! I don't want to lose images/attachments
- <a href='https://github.com/elicoidal'></a> Agree

<a href='https://www.codereviewhub.com/xie8899/project/pull/44?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/xie8899/project/pull/44?approve=1'></a>&nbsp;<a href='https://github.com/xie8899/project/pull/44'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by xie8899** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/xie8899/project/pull/44'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by elicoidal** [comment]
LGTM

**Comment by elicoidal** [comment]
@duanyp1991 Can you have a look so that we can deploy asap?

**Comment by seb-elico** [comment]
@victormartinelicocorp I thought you were supposed to port it to new API. It wasn't possible?
Also, I would like to try it with you first in order to test emails with attachments and pictures. I think we should implement something similar to issues: put the full email as a message in the conversation so that we don't lose images/attachments and formatting.

**Comment by elicoidal** [comment]
@victormartinelicocorp for new API: check odoo/master there are plenty example.
dont block this PR for this though

**Comment by elicoidal** [comment]
@seb-elico would you agree to merge and have a new PR for the migration to new API?

**Comment by seb-elico** [comment]
@elicoidal new API is not blocking indeed. However, my comment about creating a message in the thread is still valid! I don't want to lose images/attachments

**Comment by elicoidal** [comment]
Agree

**Pull request closed without merging**
